Hydrogen: hydrogen_framework::Graph Class Reference
hydrogen_framework::Graph Class Reference
#include <Graph.hpp>
Public Member Functions
Graph (unsigned ver)
~Graph ()
void addBranchEdges ()
void addEdge (Graph_Instruction *from, Graph_Instruction *to, Graph_Edge *edge)
void addFunctionCallEdges ()
void addSeqEdges (Graph_Line *line)
void addVirtualNodes (Graph_Function *func)
Graph_Instruction * findMatchedInstruction (llvm::Instruction *matchInst)
Graph_Instruction * findVirtualEntry (std::string funcName)
Graph_Instruction * findVirtualExit (std::string funcName)
std::list< Graph_Edge * > getGraphEdges ()
std::list< Graph_Function * > getGraphFunctions ()
unsigned getGraphVersion ()
unsigned getNextID ()
std::list< std::string > getWhiteList ()
bool isVirtualNodeLineNumber (unsigned lineNumber)
void printGraph (std::string graphName)
void pushGraphEdges (Graph_Edge *edge)
void pushGraphFunction (Graph_Function *func)
void setGraphVersion (unsigned ver)
Private Attributes
std::list< Graph_Edge * > graphEdges
unsigned graphEntryID
unsigned graphExitID
std::list< Graph_Function * > graphFunctions
unsigned graphID
unsigned graphVersion
std::list< std::string > whiteList
Detailed Description
Graph Class: Class for generating Graphs
Definition at line 28 of file Graph.hpp.
Constructor & Destructor Documentation
Graph()
hydrogen_framework::Graph::Graph (unsigned ver) inline
Constructor Initialize ID to zero
Definition at line 34 of file Graph.hpp.
References whiteList.
~Graph()
hydrogen_framework::Graph::~Graph () inline
Destructor
Definition at line 73 of file Graph.hpp.
References graphEdges, and graphFunctions.
Member Function Documentation
addBranchEdges()
void hydrogen_framework::Graph::addBranchEdges ()
Add branch type edges for ICFG
Definition at line 84 of file Graph.cpp.
References addEdge(), findMatchedInstruction(), graphFunctions, and graphVersion.
Referenced by hydrogen_framework::buildICFG().
addEdge()
void hydrogen_framework::Graph::addEdge (Graph_Instruction * from, Graph_Instruction * to, Graph_Edge * edge)
Function to add Graph_Edge to both graphEdges and corresponding Graph_Instruction
Definition at line 17 of file Graph.cpp.
References hydrogen_framework::Graph_Instruction::pushEdgeInstruction(), and pushGraphEdges().
Referenced by addBranchEdges(), addFunctionCallEdges(), addSeqEdges(), hydrogen_framework::addToMVICFG(), addVirtualNodes(), hydrogen_framework::deleteFromMVICFG(), and hydrogen_framework::getEdgesForAddedLines().
addFunctionCallEdges()
void hydrogen_framework::Graph::addFunctionCallEdges ()
Add function call edges Call only after addVirtualNodes
Definition at line 124 of file Graph.cpp.
References addEdge(), findVirtualEntry(), findVirtualExit(), getNextID(), getWhiteList(), graphEntryID, graphFunctions, graphVersion, hydrogen_framework::Graph_Function::pushFunctionLines(), pushGraphFunction(), hydrogen_framework::Graph_Line::pushLineInstruction(), hydrogen_framework::Graph_Function::setFunctionFile(), hydrogen_framework::Graph_Function::setFunctionName(), hydrogen_framework::Graph_Instruction::setInstructionID(), hydrogen_framework::Graph_Instruction::setInstructionLabel(), hydrogen_framework::Graph_Instruction::setInstructionPtr(), and hydrogen_framework::Graph_Line::setLineNumber().
Referenced by hydrogen_framework::buildICFG().
addSeqEdges()
void hydrogen_framework::Graph::addSeqEdges (Graph_Line * line)
Add sequential edges for the instructions in a Graph_Line
Definition at line 23 of file Graph.cpp.
References addEdge(), hydrogen_framework::Graph_Line::getLineInstructions(), and graphVersion.
Referenced by hydrogen_framework::buildICFG().
addVirtualNodes()
void hydrogen_framework::Graph::addVirtualNodes (Graph_Function * func)
Add virtual nodes and corresponding edges to the Graph_Function
Definition at line 198 of file Graph.cpp.
References addEdge(), hydrogen_framework::Graph_Function::getFunctionLines(), hydrogen_framework::Graph_Function::getFunctionName(), getNextID(), graphEntryID, graphExitID, graphVersion, hydrogen_framework::Graph_Function::pushFrontFunctionLines(), hydrogen_framework::Graph_Function::pushFunctionLines(), hydrogen_framework::Graph_Line::pushLineInstruction(), hydrogen_framework::Graph_Instruction::setInstructionID(), hydrogen_framework::Graph_Instruction::setInstructionLabel(), hydrogen_framework::Graph_Instruction::setInstructionPtr(), and hydrogen_framework::Graph_Line::setLineNumber().
Referenced by hydrogen_framework::buildICFG().
findMatchedInstruction()
Graph_Instruction * hydrogen_framework::Graph::findMatchedInstruction (llvm::Instruction * matchInst)
Find matching instruction in the ICFG Can return NULL if no match is found
Definition at line 41 of file Graph.cpp.
References graphFunctions.
Referenced by addBranchEdges().
findVirtualEntry()
Graph_Instruction * hydrogen_framework::Graph::findVirtualEntry (std::string funcName)
Find virtual entry for the given function name Can return NULL if no match is found
Definition at line 54 of file Graph.cpp.
References graphFunctions.
Referenced by addFunctionCallEdges().
findVirtualExit()
Graph_Instruction * hydrogen_framework::Graph::findVirtualExit (std::string funcName)
Find virtual entry for the given function name Can return NULL if no match is found
Definition at line 69 of file Graph.cpp.
References graphFunctions.
Referenced by addFunctionCallEdges().
getGraphEdges()
std::list<Graph_Edge *> hydrogen_framework::Graph::getGraphEdges () inline
Return graphEdges
Definition at line 165 of file Graph.hpp.
References graphEdges.
Referenced by hydrogen_framework::updateMVICFGVersion().
getGraphFunctions()
std::list<Graph_Function *> hydrogen_framework::Graph::getGraphFunctions () inline
Return graphFunctions
Definition at line 155 of file Graph.hpp.
References graphFunctions.
Referenced by hydrogen_framework::addToMVICFG(), hydrogen_framework::deleteFromMVICFG(), hydrogen_framework::findMatchedLine(), hydrogen_framework::getGraphLinesGivenLine(), hydrogen_framework::getMatchedInstructionFromGraph(), hydrogen_framework::getNewlyAdded(), and hydrogen_framework::updateMVICFGVersion().
getGraphVersion()
unsigned hydrogen_framework::Graph::getGraphVersion () inline
Return graphVersion
Definition at line 86 of file Graph.hpp.
References graphVersion.
Referenced by hydrogen_framework::addToMVICFG(), hydrogen_framework::deleteFromMVICFG(), hydrogen_framework::findMatchedLine(), hydrogen_framework::getEdgesForAddedLines(), hydrogen_framework::getGraphLinesGivenLine(), hydrogen_framework::getMatchedInstructionFromGraph(), hydrogen_framework::getNewlyAdded(), hydrogen_framework::matchedInMVICFG(), and hydrogen_framework::updateMVICFGVersion().
getNextID()
unsigned hydrogen_framework::Graph::getNextID () inline
Get next ID
Definition at line 81 of file Graph.hpp.
References graphID.
Referenced by addFunctionCallEdges(), hydrogen_framework::addToMVICFG(), addVirtualNodes(), and hydrogen_framework::buildICFG().
getWhiteList()
std::list<std::string> hydrogen_framework::Graph::getWhiteList () inline
Return whiteList
Definition at line 170 of file Graph.hpp.
References whiteList.
Referenced by addFunctionCallEdges().
isVirtualNodeLineNumber()
bool hydrogen_framework::Graph::isVirtualNodeLineNumber (unsigned lineNumber)
Return TRUE if it is a virtual node
Definition at line 340 of file Graph.cpp.
References graphEntryID, and graphExitID.
Referenced by hydrogen_framework::findMatchedLine(), and hydrogen_framework::updateMVICFGVersion().
printGraph()
void hydrogen_framework::Graph::printGraph (std::string graphName)
Print the graph in DOT format
Definition at line 226 of file Graph.cpp.
References graphEdges, graphFunctions, and graphVersion.
Referenced by main().
pushGraphEdges()
void hydrogen_framework::Graph::pushGraphEdges (Graph_Edge * edge) inline
Push Graph_Edge into graphEdges
Definition at line 96 of file Graph.hpp.
References graphEdges.
Referenced by addEdge().
pushGraphFunction()
void hydrogen_framework::Graph::pushGraphFunction (Graph_Function * func)
Push Graph_Function into graphFunctions
Definition at line 12 of file Graph.cpp.
References graphFunctions, and hydrogen_framework::Graph_Function::setGraph().
Referenced by addFunctionCallEdges(), and hydrogen_framework::buildICFG().
setGraphVersion()
void hydrogen_framework::Graph::setGraphVersion (unsigned ver) inline
Set graphVersion
Definition at line 91 of file Graph.hpp.
References graphVersion.
Referenced by main().
Field Documentation
graphEdges
std::list<Graph_Edge *> hydrogen_framework::Graph::graphEdges private
Container for Edges in the graph
Definition at line 177 of file Graph.hpp.
Referenced by getGraphEdges(), printGraph(), pushGraphEdges(), and ~Graph().
graphEntryID
unsigned hydrogen_framework::Graph::graphEntryID private
ID for all virtual entry Node. Set to max -1
Definition at line 175 of file Graph.hpp.
Referenced by addFunctionCallEdges(), addVirtualNodes(), and isVirtualNodeLineNumber().
graphExitID
unsigned hydrogen_framework::Graph::graphExitID private
ID for all virtual exit Node. Set to max -2
Definition at line 176 of file Graph.hpp.
Referenced by addVirtualNodes(), and isVirtualNodeLineNumber().
graphFunctions
std::list<Graph_Function *> hydrogen_framework::Graph::graphFunctions private
Container for function containers
Definition at line 178 of file Graph.hpp.
Referenced by addBranchEdges(), addFunctionCallEdges(), findMatchedInstruction(), findVirtualEntry(), findVirtualExit(), getGraphFunctions(), printGraph(), pushGraphFunction(), and ~Graph().
graphID
unsigned hydrogen_framework::Graph::graphID private
Unique Graph ID
Definition at line 173 of file Graph.hpp.
Referenced by getNextID().
graphVersion
unsigned hydrogen_framework::Graph::graphVersion private
Version of graph.
Definition at line 174 of file Graph.hpp.
Referenced by addBranchEdges(), addFunctionCallEdges(), addSeqEdges(), addVirtualNodes(), getGraphVersion(), printGraph(), and setGraphVersion().
whiteList
std::list<std::string> hydrogen_framework::Graph::whiteList private
Container for white-listed functions
Definition at line 179 of file Graph.hpp.
Referenced by getWhiteList(), and Graph().
The documentation for this class was generated from the following files:
Graph.hpp
Graph.cpp