Hydrogen: hydrogen_framework::Graph_Instruction Class Reference
hydrogen_framework::Graph_Instruction Class Reference
#include <Graph_Instruction.hpp>
Public Member Functions
Graph_Instruction ()
~Graph_Instruction ()
Graph_Line * getGraphLine ()
std::list< Graph_Edge * > getInstructionEdges ()
unsigned getInstructionID ()
std::string getInstructionLabel ()
llvm::Instruction * getInstructionPtr ()
std::set< Query * > getInstructionVisitedQueries ()
void insertInstructionVisitedQueries (Query *q)
void pushEdgeInstruction (Graph_Edge *edge)
void setGraphLine (Graph_Line *line)
void setInstructionID (unsigned ID)
void setInstructionLabel (std::string label)
void setInstructionPtr (llvm::Instruction *I)
Private Attributes
std::list< Graph_Edge * > instructionEdges
unsigned instructionID
std::string instructionLabel
Graph_Line * instructionLine
llvm::Instruction * instructionPtr
std::set< Query * > instructionVisitedQueries
Detailed Description
Graph_Instruction Class: To store individual LLVM instructions
Definition at line 21 of file Graph_Instruction.hpp.
Constructor & Destructor Documentation
Graph_Instruction()
hydrogen_framework::Graph_Instruction::Graph_Instruction () inline
Constructor
Definition at line 26 of file Graph_Instruction.hpp.
~Graph_Instruction()
hydrogen_framework::Graph_Instruction::~Graph_Instruction () inline
Destructor
Definition at line 31 of file Graph_Instruction.hpp.
Member Function Documentation
getGraphLine()
Graph_Line* hydrogen_framework::Graph_Instruction::getGraphLine () inline
Return pointer to encompassing Graph_Line
Definition at line 82 of file Graph_Instruction.hpp.
References instructionLine.
Referenced by hydrogen_framework::getMatchedInstructionFromGraph(), and hydrogen_framework::updateMVICFGVersion().
getInstructionEdges()
std::list<Graph_Edge *> hydrogen_framework::Graph_Instruction::getInstructionEdges () inline
Return instructionEdges
Definition at line 72 of file Graph_Instruction.hpp.
References instructionEdges.
Referenced by hydrogen_framework::getEdge(), hydrogen_framework::getEdgesForAddedLines(), hydrogen_framework::getPredGivenGraphLine(), and hydrogen_framework::getSuccGivenGraphLine().
getInstructionID()
unsigned hydrogen_framework::Graph_Instruction::getInstructionID () inline
Return instructionID
Definition at line 61 of file Graph_Instruction.hpp.
References instructionID.
getInstructionLabel()
std::string hydrogen_framework::Graph_Instruction::getInstructionLabel () inline
Return instructionLabel
Definition at line 56 of file Graph_Instruction.hpp.
References instructionLabel.
Referenced by hydrogen_framework::addToMVICFG(), hydrogen_framework::deleteFromMVICFG(), and hydrogen_framework::matchedInMVICFG().
getInstructionPtr()
llvm::Instruction* hydrogen_framework::Graph_Instruction::getInstructionPtr () inline
Get instructionPtr Can return NULL
Definition at line 67 of file Graph_Instruction.hpp.
References instructionPtr.
Referenced by hydrogen_framework::getMatchedInstructionFromGraph().
getInstructionVisitedQueries()
std::set<Query *> hydrogen_framework::Graph_Instruction::getInstructionVisitedQueries () inline
Return instructionVisitedQueries
Definition at line 87 of file Graph_Instruction.hpp.
References instructionVisitedQueries.
insertInstructionVisitedQueries()
void hydrogen_framework::Graph_Instruction::insertInstructionVisitedQueries (Query * q) inline
Insert query as pointer into instructionVisitedQueries
Definition at line 92 of file Graph_Instruction.hpp.
References instructionVisitedQueries.
pushEdgeInstruction()
void hydrogen_framework::Graph_Instruction::pushEdgeInstruction (Graph_Edge * edge) inline
Push Graph_Edge into instructionEdges list
Definition at line 51 of file Graph_Instruction.hpp.
References instructionEdges.
Referenced by hydrogen_framework::Graph::addEdge().
setGraphLine()
void hydrogen_framework::Graph_Instruction::setGraphLine (Graph_Line * line) inline
Set pointer to encompassing Graph_Line
Definition at line 77 of file Graph_Instruction.hpp.
References instructionLine.
Referenced by hydrogen_framework::Graph_Line::pushLineInstruction().
setInstructionID()
void hydrogen_framework::Graph_Instruction::setInstructionID (unsigned ID) inline
Set instructionID
Definition at line 36 of file Graph_Instruction.hpp.
References instructionID.
Referenced by hydrogen_framework::Graph::addFunctionCallEdges(), hydrogen_framework::addToMVICFG(), hydrogen_framework::Graph::addVirtualNodes(), and hydrogen_framework::buildICFG().
setInstructionLabel()
void hydrogen_framework::Graph_Instruction::setInstructionLabel (std::string label) inline
Set instructionLabel
Definition at line 41 of file Graph_Instruction.hpp.
References instructionLabel.
Referenced by hydrogen_framework::Graph::addFunctionCallEdges(), hydrogen_framework::addToMVICFG(), hydrogen_framework::Graph::addVirtualNodes(), and hydrogen_framework::buildICFG().
setInstructionPtr()
void hydrogen_framework::Graph_Instruction::setInstructionPtr (llvm::Instruction * I) inline
Set instructionPtr
Definition at line 46 of file Graph_Instruction.hpp.
References instructionPtr.
Referenced by hydrogen_framework::Graph::addFunctionCallEdges(), hydrogen_framework::addToMVICFG(), hydrogen_framework::Graph::addVirtualNodes(), and hydrogen_framework::buildICFG().
Field Documentation
instructionEdges
std::list<Graph_Edge *> hydrogen_framework::Graph_Instruction::instructionEdges private
Container for edges in the instruction
Definition at line 98 of file Graph_Instruction.hpp.
Referenced by getInstructionEdges(), and pushEdgeInstruction().
instructionID
unsigned hydrogen_framework::Graph_Instruction::instructionID private
Instruction ID
Definition at line 95 of file Graph_Instruction.hpp.
Referenced by getInstructionID(), and setInstructionID().
instructionLabel
std::string hydrogen_framework::Graph_Instruction::instructionLabel private
Instruction label or text
Definition at line 96 of file Graph_Instruction.hpp.
Referenced by getInstructionLabel(), and setInstructionLabel().
instructionLine
Graph_Line* hydrogen_framework::Graph_Instruction::instructionLine private
Points to the Graph_Line that encompasses this
Definition at line 99 of file Graph_Instruction.hpp.
Referenced by getGraphLine(), and setGraphLine().
instructionPtr
llvm::Instruction* hydrogen_framework::Graph_Instruction::instructionPtr private
Instruction LLVM Pointer
Definition at line 97 of file Graph_Instruction.hpp.
Referenced by getInstructionPtr(), and setInstructionPtr().
instructionVisitedQueries
std::set<Query *> hydrogen_framework::Graph_Instruction::instructionVisitedQueries private
Container for Queries that have visited this
Definition at line 100 of file Graph_Instruction.hpp.
Referenced by getInstructionVisitedQueries(), and insertInstructionVisitedQueries().
The documentation for this class was generated from the following file:
Graph_Instruction.hpp