Hydrogen: hydrogen_framework::Diff_Mapping Class Reference
hydrogen_framework::Diff_Mapping Class Reference
#include <Diff_Mapping.hpp>
Public Member Functions
Diff_Mapping (std::string name)
~Diff_Mapping ()
std::list< long long > getAddedLines ()
long long getAfterLineNumber (long long currLine)
long long getBeforeLineNumber (long long currLine)
std::list< long long > getDeletedLines ()
std::string getFileName ()
std::list< elemInfo > getMapping ()
std::map< long long, long long > getMatchedLines ()
void printAddedLines ()
void printDeletedLines ()
void printFileInfo ()
void printMapping ()
void printMatchedLines ()
void putMapping (std::vector< sesElem > seqVector)
Public Member Functions inherited from hydrogen_framework::Diff_Vars
Diff_Vars ()
virtual ~Diff_Vars ()
Private Attributes
std::list< long long > addedLines
std::list< long long > deletedLines
std::string fileName
std::list< elemInfo > lineMap
std::map< long long, long long > matchedLines
Additional Inherited Members
Public Types inherited from hydrogen_framework::Diff_Vars
typedef std::vector< long long > editPath
typedef std::vector< P > editPathCordinates
typedef std::string elem
typedef struct hydrogen_framework::Diff_Vars::eleminfo elemInfo
typedef std::list< elem > elemList
typedef elemList::iterator elemList_iter
typedef std::vector< elem > elemVec
typedef elemVec::iterator elemVec_iter
typedef struct hydrogen_framework::Diff_Vars::Point P
typedef std::vector< elem > sequence
typedef sequence::const_iterator sequence_const_iter
typedef sequence::iterator sequence_iter
enum SES_TYPE { SES_DELETE = -1, SES_COMMON = 0, SES_ADD = 1 }
typedef std::pair< elem, elemInfo > sesElem
typedef std::vector< sesElem > sesElemVec
typedef sesElemVec::iterator sesElemVec_iter
Data Fields inherited from hydrogen_framework::Diff_Vars
const unsigned long long MAX_CORDINATES_SIZE = 2000000
std::string SES_MARK_ADD = "+"
std::string SES_MARK_COMMON = " "
std::string SES_MARK_DELETE = "-"
Detailed Description
Diff_Mapping Class: Container for storing diff mapping details
Definition at line 18 of file Diff_Mapping.hpp.
Constructor & Destructor Documentation
Diff_Mapping()
hydrogen_framework::Diff_Mapping::Diff_Mapping (std::string name) inline
Constructor
Definition at line 23 of file Diff_Mapping.hpp.
~Diff_Mapping()
hydrogen_framework::Diff_Mapping::~Diff_Mapping () inline
Destructor
Definition at line 28 of file Diff_Mapping.hpp.
References lineMap.
Member Function Documentation
getAddedLines()
std::list<long long> hydrogen_framework::Diff_Mapping::getAddedLines () inline
Return addedLines
Definition at line 48 of file Diff_Mapping.hpp.
References addedLines.
Referenced by hydrogen_framework::addToMVICFG(), and hydrogen_framework::getNewlyAdded().
getAfterLineNumber()
long long hydrogen_framework::Diff_Mapping::getAfterLineNumber (long long currLine)
Get the afterIdx line number given the beforeIdx line number Return unsigned MAX if line not found
Definition at line 79 of file Diff_Mapping.cpp.
References lineMap.
Referenced by hydrogen_framework::findMatchedLine().
getBeforeLineNumber()
long long hydrogen_framework::Diff_Mapping::getBeforeLineNumber (long long currLine)
Get the beforeIdx line number given the afterIdx line number Return unsigned MAX if line not found
Definition at line 88 of file Diff_Mapping.cpp.
References lineMap.
Referenced by hydrogen_framework::findMatchedLine().
getDeletedLines()
std::list<long long> hydrogen_framework::Diff_Mapping::getDeletedLines () inline
Return deletedLines
Definition at line 53 of file Diff_Mapping.hpp.
References deletedLines.
Referenced by hydrogen_framework::deleteFromMVICFG().
getFileName()
std::string hydrogen_framework::Diff_Mapping::getFileName () inline
Return fileName
Definition at line 43 of file Diff_Mapping.hpp.
References fileName.
Referenced by hydrogen_framework::addToMVICFG(), hydrogen_framework::deleteFromMVICFG(), hydrogen_framework::findMatchedLine(), hydrogen_framework::matchedInMVICFG(), printFileInfo(), and hydrogen_framework::updateMVICFGVersion().
getMapping()
std::list<elemInfo> hydrogen_framework::Diff_Mapping::getMapping () inline
Return lineMap
Definition at line 38 of file Diff_Mapping.hpp.
References lineMap.
getMatchedLines()
std::map<long long, long long> hydrogen_framework::Diff_Mapping::getMatchedLines () inline
Return matchedLines
Definition at line 58 of file Diff_Mapping.hpp.
References matchedLines.
Referenced by hydrogen_framework::matchedInMVICFG().
printAddedLines()
void hydrogen_framework::Diff_Mapping::printAddedLines ()
Print addedLines
Definition at line 53 of file Diff_Mapping.cpp.
References addedLines, and hydrogen_framework::Diff_Vars::SES_MARK_ADD.
Referenced by printFileInfo().
printDeletedLines()
void hydrogen_framework::Diff_Mapping::printDeletedLines ()
Print deletedLines
Definition at line 59 of file Diff_Mapping.cpp.
References deletedLines, and hydrogen_framework::Diff_Vars::SES_MARK_DELETE.
Referenced by printFileInfo().
printFileInfo()
void hydrogen_framework::Diff_Mapping::printFileInfo ()
Print File Related Info
Definition at line 71 of file Diff_Mapping.cpp.
References getFileName(), printAddedLines(), printDeletedLines(), and printMatchedLines().
printMapping()
void hydrogen_framework::Diff_Mapping::printMapping ()
Print lineMap
Definition at line 35 of file Diff_Mapping.cpp.
References fileName, and lineMap.
printMatchedLines()
void hydrogen_framework::Diff_Mapping::printMatchedLines ()
Print matchedLines
Definition at line 65 of file Diff_Mapping.cpp.
References matchedLines.
Referenced by printFileInfo().
putMapping()
void hydrogen_framework::Diff_Mapping::putMapping (std::vector< sesElem > seqVector)
Populate line mapping
Definition at line 8 of file Diff_Mapping.cpp.
References addedLines, deletedLines, lineMap, and matchedLines.
Referenced by hydrogen_framework::generateLineMapping().
Field Documentation
addedLines
std::list<long long> hydrogen_framework::Diff_Mapping::addedLines private
Container for added line numbers
Definition at line 100 of file Diff_Mapping.hpp.
Referenced by getAddedLines(), printAddedLines(), and putMapping().
deletedLines
std::list<long long> hydrogen_framework::Diff_Mapping::deletedLines private
Container for deleted line numbers
Definition at line 101 of file Diff_Mapping.hpp.
Referenced by getDeletedLines(), printDeletedLines(), and putMapping().
fileName
std::string hydrogen_framework::Diff_Mapping::fileName private
File Name
Definition at line 98 of file Diff_Mapping.hpp.
Referenced by getFileName(), and printMapping().
lineMap
std::list<elemInfo> hydrogen_framework::Diff_Mapping::lineMap private
Container for line mapping
Definition at line 99 of file Diff_Mapping.hpp.
Referenced by getAfterLineNumber(), getBeforeLineNumber(), getMapping(), printMapping(), putMapping(), and ~Diff_Mapping().
matchedLines
std::map<long long, long long> hydrogen_framework::Diff_Mapping::matchedLines private
Container for matched line numbers mapping from before to after lines
Definition at line 103 of file Diff_Mapping.hpp.
Referenced by getMatchedLines(), printMatchedLines(), and putMapping().
The documentation for this class was generated from the following files:
Diff_Mapping.hpp
Diff_Mapping.cpp