Hydrogen: Graph.hpp File Reference
Graph.hpp File Reference
#include <fstream>
#include <iostream>
#include <list>
#include <llvm/IR/CallSite.h>
#include <llvm/IR/DebugInfoMetadata.h>
#include <llvm/IR/InstrTypes.h>
#include <llvm/IR/Intrinsics.h>
#include <regex>
Data Structures
class hydrogen_framework::Graph
Functions
void hydrogen_framework::getLocationInfo (llvm::Instruction &I, unsigned int &DILocLine, std::string &DIFile)
Detailed Description
Author
Ashwin K J
Graph Class: Graph Data-structure
Definition in file Graph.hpp.
Function Documentation
getLocationInfo()
void hydrogen_framework::getLocationInfo (llvm::Instruction & I, unsigned int & DILocLine, std::string & DIFile)
Find the line number and file name of the given LLVM instruction Will return 0 if no information found
Definition at line 296 of file Graph.cpp.
References hydrogen_framework::getLocationInfo().
Referenced by hydrogen_framework::buildICFG(), and hydrogen_framework::getLocationInfo().