Hydrogen: Hydrogen.cpp File Reference
Hydrogen.cpp File Reference
#include "Diff_Mapping.hpp"
#include "Get_Input.hpp"
#include "Graph.hpp"
#include "Graph_Line.hpp"
#include "MVICFG.hpp"
#include "Module.hpp"
#include <chrono>
Functions
int main (int argc, char *argv[])
Detailed Description
Author
Ashwin K J
Definition in file Hydrogen.cpp.
Function Documentation
main()
int main (int argc, char * argv[])
Main function
<Map From ICFG Graph_Line to MVICFG Graph_Line
Definition at line 18 of file Hydrogen.cpp.
References hydrogen_framework::addToMVICFG(), hydrogen_framework::buildICFG(), hydrogen_framework::deleteFromMVICFG(), hydrogen_framework::generateLineMapping(), hydrogen_framework::getEdgesForAddedLines(), hydrogen_framework::Hydrogen::getModules(), hydrogen_framework::matchedInMVICFG(), hydrogen_framework::Graph::printGraph(), hydrogen_framework::Hydrogen::processInputs(), hydrogen_framework::Graph::setGraphVersion(), hydrogen_framework::updateMVICFGVersion(), and hydrogen_framework::Hydrogen::validateInputs().