Hydrogen: hydrogen_framework::Diff_Ses Class Reference
hydrogen_framework::Diff_Ses Class Reference
#include <Diff_Util.hpp>
Public Member Functions
Diff_Ses ()
Diff_Ses (bool moveDel)
~Diff_Ses ()
void addSequence (elem e, long long beforeIdx, long long afterIdx, const int type)
sesElemVec getSequence () const
bool isChange () const
bool isOnlyAdd () const
bool isOnlyCopy () const
bool isOnlyDelete () const
bool isOnlyOneOperation () const
Public Member Functions inherited from hydrogen_framework::Diff_Sequence
Diff_Sequence ()
virtual ~Diff_Sequence ()
void addSequence (elem e)
elemVec getSequence () const
Public Member Functions inherited from hydrogen_framework::Diff_Vars
Diff_Vars ()
virtual ~Diff_Vars ()
Private Attributes
bool deletesFirst
size_t nextDeleteIdx
bool onlyAdd
bool onlyCopy
bool onlyDelete
sesElemVec sequenceDS
Additional Inherited Members
Public Types inherited from hydrogen_framework::Diff_Vars
typedef std::vector< long long > editPath
typedef std::vector< P > editPathCordinates
typedef std::string elem
typedef struct hydrogen_framework::Diff_Vars::eleminfo elemInfo
typedef std::list< elem > elemList
typedef elemList::iterator elemList_iter
typedef std::vector< elem > elemVec
typedef elemVec::iterator elemVec_iter
typedef struct hydrogen_framework::Diff_Vars::Point P
typedef std::vector< elem > sequence
typedef sequence::const_iterator sequence_const_iter
typedef sequence::iterator sequence_iter
enum SES_TYPE { SES_DELETE = -1, SES_COMMON = 0, SES_ADD = 1 }
typedef std::pair< elem, elemInfo > sesElem
typedef std::vector< sesElem > sesElemVec
typedef sesElemVec::iterator sesElemVec_iter
Data Fields inherited from hydrogen_framework::Diff_Vars
const unsigned long long MAX_CORDINATES_SIZE = 2000000
std::string SES_MARK_ADD = "+"
std::string SES_MARK_COMMON = " "
std::string SES_MARK_DELETE = "-"
Protected Attributes inherited from hydrogen_framework::Diff_Sequence
elemVec sequence
Detailed Description
Class to compute Shortest Edit Distance
Definition at line 129 of file Diff_Util.hpp.
Constructor & Destructor Documentation
Diff_Ses() [1/2]
hydrogen_framework::Diff_Ses::Diff_Ses () inline
Constructor with no argument
Definition at line 134 of file Diff_Util.hpp.
References nextDeleteIdx.
Diff_Ses() [2/2]
hydrogen_framework::Diff_Ses::Diff_Ses (bool moveDel) inline
Constructor with one argument
Definition at line 139 of file Diff_Util.hpp.
References nextDeleteIdx.
~Diff_Ses()
hydrogen_framework::Diff_Ses::~Diff_Ses () inline
Destructor
Definition at line 144 of file Diff_Util.hpp.
Member Function Documentation
addSequence()
void hydrogen_framework::Diff_Ses::addSequence (elem e, long long beforeIdx, long long afterIdx, const int type)
Add sequence
Definition at line 8 of file Diff_Util.cpp.
References hydrogen_framework::Diff_Vars::eleminfo::afterIdx, hydrogen_framework::Diff_Vars::eleminfo::beforeIdx, deletesFirst, nextDeleteIdx, onlyAdd, onlyCopy, onlyDelete, sequenceDS, and hydrogen_framework::Diff_Vars::eleminfo::type.
Referenced by hydrogen_framework::Diff_Util::recordSequence().
getSequence()
sesElemVec hydrogen_framework::Diff_Ses::getSequence () const inline
Return sequence
Definition at line 179 of file Diff_Util.hpp.
References sequenceDS.
Referenced by hydrogen_framework::generateLineMapping().
isChange()
bool hydrogen_framework::Diff_Ses::isChange () const inline
Return TRUE if onlyCopy is FALSE
Definition at line 169 of file Diff_Util.hpp.
References onlyCopy.
isOnlyAdd()
bool hydrogen_framework::Diff_Ses::isOnlyAdd () const inline
Return onlyAdd
Definition at line 149 of file Diff_Util.hpp.
References onlyAdd.
Referenced by isOnlyOneOperation().
isOnlyCopy()
bool hydrogen_framework::Diff_Ses::isOnlyCopy () const inline
Return onlyCopy
Definition at line 159 of file Diff_Util.hpp.
References onlyCopy.
Referenced by isOnlyOneOperation().
isOnlyDelete()
bool hydrogen_framework::Diff_Ses::isOnlyDelete () const inline
Return onlyDelete
Definition at line 154 of file Diff_Util.hpp.
References onlyDelete.
Referenced by isOnlyOneOperation().
isOnlyOneOperation()
bool hydrogen_framework::Diff_Ses::isOnlyOneOperation () const inline
Return TRUE if any of onlyAdd, onlyDelete or onlyCopy is TRUE
Definition at line 164 of file Diff_Util.hpp.
References isOnlyAdd(), isOnlyCopy(), and isOnlyDelete().
Field Documentation
deletesFirst
bool hydrogen_framework::Diff_Ses::deletesFirst private
Flag to indicate if deletion is required first
Definition at line 186 of file Diff_Util.hpp.
Referenced by addSequence().
nextDeleteIdx
size_t hydrogen_framework::Diff_Ses::nextDeleteIdx private
Point towards next deletion ID
Definition at line 187 of file Diff_Util.hpp.
Referenced by addSequence(), and Diff_Ses().
onlyAdd
bool hydrogen_framework::Diff_Ses::onlyAdd private
Flag to indicate add operation
Definition at line 183 of file Diff_Util.hpp.
Referenced by addSequence(), and isOnlyAdd().
onlyCopy
bool hydrogen_framework::Diff_Ses::onlyCopy private
Flag to indicate change operation
Definition at line 185 of file Diff_Util.hpp.
Referenced by addSequence(), isChange(), and isOnlyCopy().
onlyDelete
bool hydrogen_framework::Diff_Ses::onlyDelete private
Flag to indicate deletion operation
Definition at line 184 of file Diff_Util.hpp.
Referenced by addSequence(), and isOnlyDelete().
sequenceDS
sesElemVec hydrogen_framework::Diff_Ses::sequenceDS private
SES sequence
Definition at line 182 of file Diff_Util.hpp.
Referenced by addSequence(), and getSequence().
The documentation for this class was generated from the following files:
Diff_Util.hpp
Diff_Util.cpp