Hydrogen: MVICFG.cpp File Reference
MVICFG.cpp File Reference
#include "MVICFG.hpp"
#include "Diff_Mapping.hpp"
#include "Graph.hpp"
#include "Graph_Edge.hpp"
#include "Graph_Function.hpp"
#include "Graph_Instruction.hpp"
#include "Graph_Line.hpp"
#include "Module.hpp"
Functions
std::list< Graph_Line * > hydrogen_framework::addToMVICFG (Graph *MVICFG, Graph *ICFG, Diff_Mapping diff, unsigned Version)
Graph * hydrogen_framework::buildICFG (Module *mod, unsigned graphVersion)
std::list< Graph_Line * > hydrogen_framework::deleteFromMVICFG (Graph *MVICFG, Graph *ICFG, Diff_Mapping diff, unsigned Version)
Graph_Line * hydrogen_framework::findMatchedLine (Graph_Line *t, Graph *matchTo, Graph *matchFrom, Diff_Mapping diff)
std::list< Diff_Mapping > hydrogen_framework::generateLineMapping (Module *firstMod, Module *secondMod)
Graph_Edge * hydrogen_framework::getEdge (Graph_Instruction *fromNode, Graph_Instruction *toNode, Graph_Edge::edgeTypes type)
void hydrogen_framework::getEdgesForAddedLines (Graph *MVICFG, Graph *ICFG, std::list< Graph_Line * > addedLines, std::list< Diff_Mapping > diffMap, unsigned Version)
std::string hydrogen_framework::getGraphLineInstructionsAsString (Graph_Line *line)
std::list< Graph_Line * > hydrogen_framework::getGraphLinesGivenLine (Graph *graph, long long lineNo, std::string fileName)
Graph_Edge * hydrogen_framework::getInBetweenEdge (Graph_Line *fromLine, Graph_Line *toLine)
Graph_Instruction * hydrogen_framework::getMatchedInstructionFromGraph (Graph *graphToMatch, Graph_Instruction *instToMatch)
Graph_Line * hydrogen_framework::getNewlyAdded (Graph *MVICFG, Graph *ICFG, Graph_Line *newLine, Diff_Mapping diff)
std::list< Graph_Line * > hydrogen_framework::getPredGivenGraphLine (Graph_Line *line)
std::list< Graph_Line * > hydrogen_framework::getSuccGivenGraphLine (Graph_Line *line)
std::map< Graph_Line *, Graph_Line * > hydrogen_framework::matchedInMVICFG (Graph *MVICFG, Graph *ICFG, Diff_Mapping diff, unsigned Version)
Graph_Line * hydrogen_framework::resolveMatchedLinesWithNoExtactStringMatch (std::list< Graph_Line * > matchedLines, std::string lineFromString, unsigned int graphVersion)
void hydrogen_framework::updateMVICFGVersion (Graph *MVICFG, std::list< Graph_Line * > addedLines, std::list< Graph_Line * > deletedLines, std::list< Diff_Mapping > diffMap, unsigned Version)
Detailed Description
Author
Ashwin K J
Implementing MVICFG.hpp
Definition in file MVICFG.cpp.
Function Documentation
addToMVICFG()
std::list< Graph_Line * > hydrogen_framework::addToMVICFG (Graph * MVICFG, Graph * ICFG, Diff_Mapping diff, unsigned Version)
Add nodes to MVICFG and returns the added MVICFG lines
Definition at line 349 of file MVICFG.cpp.
References hydrogen_framework::Graph::addEdge(), hydrogen_framework::addToMVICFG(), hydrogen_framework::findMatchedLine(), hydrogen_framework::Diff_Mapping::getAddedLines(), hydrogen_framework::getEdge(), hydrogen_framework::Graph_Edge::getEdgeType(), hydrogen_framework::Diff_Mapping::getFileName(), hydrogen_framework::Graph_Function::getFunctionFile(), hydrogen_framework::Graph_Function::getFunctionName(), hydrogen_framework::Graph::getGraphFunctions(), hydrogen_framework::getGraphLinesGivenLine(), hydrogen_framework::Graph::getGraphVersion(), hydrogen_framework::getInBetweenEdge(), hydrogen_framework::Graph_Instruction::getInstructionLabel(), hydrogen_framework::Graph_Line::getLineInstructions(), hydrogen_framework::Graph::getNextID(), hydrogen_framework::getPredGivenGraphLine(), hydrogen_framework::getSuccGivenGraphLine(), hydrogen_framework::Graph_Edge::pushEdgeVersions(), hydrogen_framework::Graph_Line::pushLineInstruction(), hydrogen_framework::Graph_Function::setFunctionName(), hydrogen_framework::Graph_Instruction::setInstructionID(), hydrogen_framework::Graph_Instruction::setInstructionLabel(), hydrogen_framework::Graph_Instruction::setInstructionPtr(), and hydrogen_framework::Graph_Line::setLineNumber().
Referenced by hydrogen_framework::addToMVICFG(), and main().
buildICFG()
Graph * hydrogen_framework::buildICFG (Module * mod, unsigned graphVersion)
Build ICFG for the given module
Definition at line 15 of file MVICFG.cpp.
References hydrogen_framework::Graph::addBranchEdges(), hydrogen_framework::Graph::addFunctionCallEdges(), hydrogen_framework::Graph::addSeqEdges(), hydrogen_framework::Graph::addVirtualNodes(), hydrogen_framework::buildICFG(), hydrogen_framework::Graph_Line::getLineNumber(), hydrogen_framework::getLocationInfo(), hydrogen_framework::Graph::getNextID(), hydrogen_framework::Module::getPtr(), hydrogen_framework::Graph_Function::isFunctionFileSet(), hydrogen_framework::Graph_Function::isFunctionLinesEmpty(), hydrogen_framework::Graph_Line::isLineInstructionEmpty(), hydrogen_framework::Graph_Function::pushFunctionLines(), hydrogen_framework::Graph::pushGraphFunction(), hydrogen_framework::Graph_Line::pushLineInstruction(), hydrogen_framework::Graph_Function::setFunctionFile(), hydrogen_framework::Graph_Function::setFunctionName(), hydrogen_framework::Graph_Instruction::setInstructionID(), hydrogen_framework::Graph_Instruction::setInstructionLabel(), hydrogen_framework::Graph_Instruction::setInstructionPtr(), and hydrogen_framework::Graph_Line::setLineNumber().
Referenced by hydrogen_framework::buildICFG(), and main().
deleteFromMVICFG()
std::list< Graph_Line * > hydrogen_framework::deleteFromMVICFG (Graph * MVICFG, Graph * ICFG, Diff_Mapping diff, unsigned Version)
Mark deleted nodes in MVICFG and returns the deleted MVICFG lines
Definition at line 556 of file MVICFG.cpp.
References hydrogen_framework::Graph::addEdge(), hydrogen_framework::deleteFromMVICFG(), hydrogen_framework::findMatchedLine(), hydrogen_framework::Diff_Mapping::getDeletedLines(), hydrogen_framework::getEdge(), hydrogen_framework::Graph_Edge::getEdgeType(), hydrogen_framework::Diff_Mapping::getFileName(), hydrogen_framework::Graph::getGraphFunctions(), hydrogen_framework::getGraphLinesGivenLine(), hydrogen_framework::Graph::getGraphVersion(), hydrogen_framework::getInBetweenEdge(), hydrogen_framework::Graph_Instruction::getInstructionLabel(), hydrogen_framework::Graph_Line::getLineInstructions(), hydrogen_framework::getNewlyAdded(), hydrogen_framework::getPredGivenGraphLine(), and hydrogen_framework::getSuccGivenGraphLine().
Referenced by hydrogen_framework::deleteFromMVICFG(), and main().
findMatchedLine()
Graph_Line * hydrogen_framework::findMatchedLine (Graph_Line * t, Graph * matchTo, Graph * matchFrom, Diff_Mapping diff)
Find matched Node Returns NULL if no match found Always make sure to check that the Graph_Line is from the diff being used
Definition at line 233 of file MVICFG.cpp.
References hydrogen_framework::findMatchedLine(), hydrogen_framework::Diff_Mapping::getAfterLineNumber(), hydrogen_framework::Diff_Mapping::getBeforeLineNumber(), hydrogen_framework::Diff_Mapping::getFileName(), hydrogen_framework::Graph_Function::getFunctionFile(), hydrogen_framework::Graph_Function::getFunctionName(), hydrogen_framework::Graph_Line::getGraphFunction(), hydrogen_framework::Graph::getGraphFunctions(), hydrogen_framework::getGraphLineInstructionsAsString(), hydrogen_framework::Graph::getGraphVersion(), hydrogen_framework::Graph_Line::getLineNumber(), hydrogen_framework::Graph::isVirtualNodeLineNumber(), and hydrogen_framework::resolveMatchedLinesWithNoExtactStringMatch().
Referenced by hydrogen_framework::addToMVICFG(), hydrogen_framework::deleteFromMVICFG(), hydrogen_framework::findMatchedLine(), and hydrogen_framework::matchedInMVICFG().
generateLineMapping()
std::list< Diff_Mapping > hydrogen_framework::generateLineMapping (Module * firstMod, Module * secondMod)
Generate Line Mappings between two modules
Definition at line 75 of file MVICFG.cpp.
References hydrogen_framework::Diff_Util::compose(), hydrogen_framework::generateLineMapping(), hydrogen_framework::Diff_Ses::getSequence(), hydrogen_framework::Diff_Util::getSes(), and hydrogen_framework::Diff_Mapping::putMapping().
Referenced by hydrogen_framework::generateLineMapping(), and main().
getEdge()
Graph_Edge * hydrogen_framework::getEdge (Graph_Instruction * fromNode, Graph_Instruction * toNode, Graph_Edge::edgeTypes type)
Get the edge between two given nodes Returns NULL if no match found
Definition at line 300 of file MVICFG.cpp.
References hydrogen_framework::getEdge(), and hydrogen_framework::Graph_Instruction::getInstructionEdges().
Referenced by hydrogen_framework::addToMVICFG(), hydrogen_framework::deleteFromMVICFG(), hydrogen_framework::getEdge(), hydrogen_framework::getEdgesForAddedLines(), hydrogen_framework::getInBetweenEdge(), and hydrogen_framework::matchedInMVICFG().
getEdgesForAddedLines()
void hydrogen_framework::getEdgesForAddedLines (Graph * MVICFG, Graph * ICFG, std::list< Graph_Line * > addedLines, std::list< Diff_Mapping > diffMap, unsigned Version)
Import edges from ICFG instruction for added Graph_Line
Definition at line 523 of file MVICFG.cpp.
References hydrogen_framework::Graph::addEdge(), hydrogen_framework::getEdge(), hydrogen_framework::getEdgesForAddedLines(), hydrogen_framework::Graph::getGraphVersion(), hydrogen_framework::Graph_Instruction::getInstructionEdges(), and hydrogen_framework::getMatchedInstructionFromGraph().
Referenced by hydrogen_framework::getEdgesForAddedLines(), and main().
getGraphLineInstructionsAsString()
std::string hydrogen_framework::getGraphLineInstructionsAsString (Graph_Line * line)
Get the OpCode of the Instructions in a Graph_Line as String in the order in which they appear Returns empty string if none of the Graph_Instruction had Instruction_Ptr
Definition at line 185 of file MVICFG.cpp.
References hydrogen_framework::getGraphLineInstructionsAsString(), and hydrogen_framework::Graph_Line::getLineInstructions().
Referenced by hydrogen_framework::findMatchedLine(), hydrogen_framework::getGraphLineInstructionsAsString(), and hydrogen_framework::resolveMatchedLinesWithNoExtactStringMatch().
getGraphLinesGivenLine()
std::list< Graph_Line * > hydrogen_framework::getGraphLinesGivenLine (Graph * graph, long long lineNo, std::string fileName)
Get Graph_Line(s) from given source line Returns empty list if no Graph_Line is not found
Definition at line 139 of file MVICFG.cpp.
References hydrogen_framework::Graph::getGraphFunctions(), hydrogen_framework::getGraphLinesGivenLine(), and hydrogen_framework::Graph::getGraphVersion().
Referenced by hydrogen_framework::addToMVICFG(), hydrogen_framework::deleteFromMVICFG(), hydrogen_framework::getGraphLinesGivenLine(), and hydrogen_framework::matchedInMVICFG().
getInBetweenEdge()
Graph_Edge * hydrogen_framework::getInBetweenEdge (Graph_Line * fromLine, Graph_Line * toLine)
Get the first edge between two Graph_Line It does reverse propagation for Instructions of fromLine and forward propagation for toLine Instructions Used only when getEdge fails to find an edge where one is expected Returns NULL if no match is found
Definition at line 315 of file MVICFG.cpp.
References hydrogen_framework::getEdge(), hydrogen_framework::getInBetweenEdge(), and hydrogen_framework::Graph_Line::getLineInstructions().
Referenced by hydrogen_framework::addToMVICFG(), hydrogen_framework::deleteFromMVICFG(), hydrogen_framework::getInBetweenEdge(), and hydrogen_framework::matchedInMVICFG().
getMatchedInstructionFromGraph()
Graph_Instruction * hydrogen_framework::getMatchedInstructionFromGraph (Graph * graphToMatch, Graph_Instruction * instToMatch)
Get matching Graph_Instruction from given Graph given a Graph_Instruction using LLVM PTR Return NULL if no match is found
Definition at line 499 of file MVICFG.cpp.
References hydrogen_framework::Graph::getGraphFunctions(), hydrogen_framework::Graph_Instruction::getGraphLine(), hydrogen_framework::Graph::getGraphVersion(), hydrogen_framework::Graph_Instruction::getInstructionPtr(), hydrogen_framework::Graph_Line::getLineNumber(), and hydrogen_framework::getMatchedInstructionFromGraph().
Referenced by hydrogen_framework::getEdgesForAddedLines(), and hydrogen_framework::getMatchedInstructionFromGraph().
getNewlyAdded()
Graph_Line * hydrogen_framework::getNewlyAdded (Graph * MVICFG, Graph * ICFG, Graph_Line * newLine, Diff_Mapping diff)
Get the newly added MVICFG Graph_Line corresponding to the given ICFG Graph_Line Used only when findMatchedLine fails to retrieve the same Returns NULL if no such line is found
Definition at line 330 of file MVICFG.cpp.
References hydrogen_framework::Diff_Mapping::getAddedLines(), hydrogen_framework::Graph_Function::getFunctionFile(), hydrogen_framework::Graph_Line::getGraphFunction(), hydrogen_framework::Graph::getGraphFunctions(), hydrogen_framework::Graph::getGraphVersion(), hydrogen_framework::Graph_Line::getLineNumber(), and hydrogen_framework::getNewlyAdded().
Referenced by hydrogen_framework::deleteFromMVICFG(), and hydrogen_framework::getNewlyAdded().
getPredGivenGraphLine()
std::list< Graph_Line * > hydrogen_framework::getPredGivenGraphLine (Graph_Line * line)
Get predecessor of a given Graph_Line
Definition at line 161 of file MVICFG.cpp.
References hydrogen_framework::Graph_Instruction::getInstructionEdges(), hydrogen_framework::Graph_Line::getLineInstructions(), and hydrogen_framework::getPredGivenGraphLine().
Referenced by hydrogen_framework::addToMVICFG(), hydrogen_framework::deleteFromMVICFG(), hydrogen_framework::getPredGivenGraphLine(), and hydrogen_framework::matchedInMVICFG().
getSuccGivenGraphLine()
std::list< Graph_Line * > hydrogen_framework::getSuccGivenGraphLine (Graph_Line * line)
Get successor of a given Graph_Line
Definition at line 173 of file MVICFG.cpp.
References hydrogen_framework::Graph_Instruction::getInstructionEdges(), hydrogen_framework::Graph_Line::getLineInstructions(), and hydrogen_framework::getSuccGivenGraphLine().
Referenced by hydrogen_framework::addToMVICFG(), hydrogen_framework::deleteFromMVICFG(), hydrogen_framework::getSuccGivenGraphLine(), and hydrogen_framework::matchedInMVICFG().
matchedInMVICFG()
std::map< Graph_Line *, Graph_Line * > hydrogen_framework::matchedInMVICFG (Graph * MVICFG, Graph * ICFG, Diff_Mapping diff, unsigned Version)
Returns the corresponding matched Graph_Line in MVICFG from ICFG
Definition at line 703 of file MVICFG.cpp.
References hydrogen_framework::findMatchedLine(), hydrogen_framework::getEdge(), hydrogen_framework::Diff_Mapping::getFileName(), hydrogen_framework::getGraphLinesGivenLine(), hydrogen_framework::Graph::getGraphVersion(), hydrogen_framework::getInBetweenEdge(), hydrogen_framework::Graph_Instruction::getInstructionLabel(), hydrogen_framework::Graph_Line::getLineInstructions(), hydrogen_framework::Diff_Mapping::getMatchedLines(), hydrogen_framework::getPredGivenGraphLine(), hydrogen_framework::getSuccGivenGraphLine(), hydrogen_framework::Graph_Edge::isPartOfGraph(), hydrogen_framework::matchedInMVICFG(), and hydrogen_framework::Graph_Edge::pushEdgeVersions().
Referenced by main(), and hydrogen_framework::matchedInMVICFG().
resolveMatchedLinesWithNoExtactStringMatch()
Graph_Line * hydrogen_framework::resolveMatchedLinesWithNoExtactStringMatch (std::list< Graph_Line * > matchedLines, std::string lineFromString, unsigned int graphVersion)
Heuristically try to find the closest Graph_Line match from a list of potential Graph_Line matches when no exact match is found using getGraphLineInstructionsAsString Currently will throw an warning if heuristic skips more than 2 OpCode to match the lines Returns NULL if no heuristic match is found
Definition at line 200 of file MVICFG.cpp.
References hydrogen_framework::getGraphLineInstructionsAsString(), hydrogen_framework::Graph_Line::getLineNumber(), and hydrogen_framework::resolveMatchedLinesWithNoExtactStringMatch().
Referenced by hydrogen_framework::findMatchedLine(), and hydrogen_framework::resolveMatchedLinesWithNoExtactStringMatch().
updateMVICFGVersion()
void hydrogen_framework::updateMVICFGVersion (Graph * MVICFG, std::list< Graph_Line * > addedLines, std::list< Graph_Line * > deletedLines, std::list< Diff_Mapping > diffMap, unsigned Version)
Update the Edge and Node information for MVICFG
Definition at line 814 of file MVICFG.cpp.
References hydrogen_framework::Diff_Mapping::getFileName(), hydrogen_framework::Graph::getGraphEdges(), hydrogen_framework::Graph::getGraphFunctions(), hydrogen_framework::Graph_Instruction::getGraphLine(), hydrogen_framework::Graph::getGraphVersion(), hydrogen_framework::Graph_Line::getLineNumber(), hydrogen_framework::Graph::isVirtualNodeLineNumber(), and hydrogen_framework::updateMVICFGVersion().
Referenced by main(), and hydrogen_framework::updateMVICFGVersion().