Hydrogen: Graph.cpp File Reference
Graph.cpp File Reference
#include "Graph.hpp"
#include "Graph_Edge.hpp"
#include "Graph_Function.hpp"
#include "Graph_Instruction.hpp"
#include "Graph_Line.hpp"
Functions
void hydrogen_framework::getLocationInfo (llvm::Instruction &I, unsigned int &DILocLine, std::string &DIFile)
Detailed Description
Author
Ashwin K J
Implementing Graph.hpp
Definition in file Graph.cpp.
Function Documentation
getLocationInfo()
void hydrogen_framework::getLocationInfo (llvm::Instruction & I, unsigned int & DILocLine, std::string & DIFile)
Find the line number and file name of the given LLVM instruction Will return 0 if no information found
Definition at line 296 of file Graph.cpp.
References hydrogen_framework::getLocationInfo().
Referenced by hydrogen_framework::buildICFG(), and hydrogen_framework::getLocationInfo().