Hydrogen: hydrogen_framework::Graph_Line Class Reference
hydrogen_framework::Graph_Line Class Reference
#include <Graph_Line.hpp>
Public Member Functions
Graph_Line (unsigned Version)
~Graph_Line ()
Graph_Function * getGraphFunction ()
unsigned getLineGraphVersion ()
std::list< Graph_Instruction * > getLineInstructions ()
unsigned getLineNumber (unsigned Version)
bool isLineInstructionEmpty ()
void pushLineInstruction (Graph_Instruction *inst)
void setGraphFunction (Graph_Function *func)
void setLineNumber (unsigned Version, unsigned line)
Private Attributes
Graph_Function * lineFunction
unsigned lineGraphVersion
std::list< Graph_Instruction * > lineInstructions
std::map< unsigned, unsigned > lineNumber
Detailed Description
Graph_Line Class: Container for storing LLVM instruction belonging to a line
Definition at line 19 of file Graph_Line.hpp.
Constructor & Destructor Documentation
Graph_Line()
hydrogen_framework::Graph_Line::Graph_Line (unsigned Version) inline
Constructor
Definition at line 24 of file Graph_Line.hpp.
~Graph_Line()
hydrogen_framework::Graph_Line::~Graph_Line () inline
Destructor
Definition at line 29 of file Graph_Line.hpp.
References lineInstructions.
Member Function Documentation
getGraphFunction()
Graph_Function* hydrogen_framework::Graph_Line::getGraphFunction () inline
Return pointer to encompassing Graph_Line
Definition at line 65 of file Graph_Line.hpp.
References lineFunction.
Referenced by hydrogen_framework::findMatchedLine(), and hydrogen_framework::getNewlyAdded().
getLineGraphVersion()
unsigned hydrogen_framework::Graph_Line::getLineGraphVersion () inline
Return lineGraphVersion
Definition at line 70 of file Graph_Line.hpp.
References lineGraphVersion.
getLineInstructions()
std::list<Graph_Instruction *> hydrogen_framework::Graph_Line::getLineInstructions () inline
Return lineInstructions
Definition at line 55 of file Graph_Line.hpp.
References lineInstructions.
Referenced by hydrogen_framework::Graph::addSeqEdges(), hydrogen_framework::addToMVICFG(), hydrogen_framework::deleteFromMVICFG(), hydrogen_framework::getGraphLineInstructionsAsString(), hydrogen_framework::getInBetweenEdge(), hydrogen_framework::getPredGivenGraphLine(), hydrogen_framework::getSuccGivenGraphLine(), and hydrogen_framework::matchedInMVICFG().
getLineNumber()
unsigned hydrogen_framework::Graph_Line::getLineNumber (unsigned Version)
Get lineNumber given a version Returns zero if no mapping found
Definition at line 20 of file Graph_Line.cpp.
References lineNumber.
Referenced by hydrogen_framework::buildICFG(), hydrogen_framework::findMatchedLine(), hydrogen_framework::getMatchedInstructionFromGraph(), hydrogen_framework::getNewlyAdded(), hydrogen_framework::resolveMatchedLinesWithNoExtactStringMatch(), and hydrogen_framework::updateMVICFGVersion().
isLineInstructionEmpty()
bool hydrogen_framework::Graph_Line::isLineInstructionEmpty () inline
Return true if lineInstructions is empty
Definition at line 45 of file Graph_Line.hpp.
References lineInstructions.
Referenced by hydrogen_framework::buildICFG().
pushLineInstruction()
void hydrogen_framework::Graph_Line::pushLineInstruction (Graph_Instruction * inst)
Push the Graph_Instruction at the back of the list
Definition at line 15 of file Graph_Line.cpp.
References lineInstructions, and hydrogen_framework::Graph_Instruction::setGraphLine().
Referenced by hydrogen_framework::Graph::addFunctionCallEdges(), hydrogen_framework::addToMVICFG(), hydrogen_framework::Graph::addVirtualNodes(), and hydrogen_framework::buildICFG().
setGraphFunction()
void hydrogen_framework::Graph_Line::setGraphFunction (Graph_Function * func) inline
Set pointer to encompassing Graph_Function
Definition at line 60 of file Graph_Line.hpp.
References lineFunction.
Referenced by hydrogen_framework::Graph_Function::pushFrontFunctionLines(), and hydrogen_framework::Graph_Function::pushFunctionLines().
setLineNumber()
void hydrogen_framework::Graph_Line::setLineNumber (unsigned Version, unsigned line)
Set lineNumber
Definition at line 11 of file Graph_Line.cpp.
References lineNumber.
Referenced by hydrogen_framework::Graph::addFunctionCallEdges(), hydrogen_framework::addToMVICFG(), hydrogen_framework::Graph::addVirtualNodes(), and hydrogen_framework::buildICFG().
Field Documentation
lineFunction
Graph_Function* hydrogen_framework::Graph_Line::lineFunction private
Points to the Graph_Function that encompasses this
Definition at line 75 of file Graph_Line.hpp.
Referenced by getGraphFunction(), and setGraphFunction().
lineGraphVersion
unsigned hydrogen_framework::Graph_Line::lineGraphVersion private
The graph version in which this line was introduced
Definition at line 76 of file Graph_Line.hpp.
Referenced by getLineGraphVersion().
lineInstructions
std::list<Graph_Instruction *> hydrogen_framework::Graph_Line::lineInstructions private
Container for instruction in the line
Definition at line 74 of file Graph_Line.hpp.
Referenced by getLineInstructions(), isLineInstructionEmpty(), pushLineInstruction(), and ~Graph_Line().
lineNumber
std::map<unsigned, unsigned> hydrogen_framework::Graph_Line::lineNumber private
Map between graphVersion and line Number
Definition at line 73 of file Graph_Line.hpp.
Referenced by getLineNumber(), and setLineNumber().
The documentation for this class was generated from the following files:
Graph_Line.hpp
Graph_Line.cpp