Hydrogen: hydrogen_framework::Hydrogen Class Reference
hydrogen_framework::Hydrogen Class Reference
#include <Get_Input.hpp>
Public Member Functions
Hydrogen ()
~Hydrogen ()
std::list< Module * > getModules ()
bool processInputs (int c, char *files[])
bool validateInputs (int c, char *files[])
Private Attributes
std::string hydrogenDemarcation
std::list< Module * > hydrogenModules
Detailed Description
Hydrogen Class: Hydrogen Framework data structures and functions
Definition at line 21 of file Get_Input.hpp.
Constructor & Destructor Documentation
Hydrogen()
hydrogen_framework::Hydrogen::Hydrogen () inline
Constructor for hydrogen class Sets the demarcation variable
Definition at line 27 of file Get_Input.hpp.
References hydrogenDemarcation.
~Hydrogen()
hydrogen_framework::Hydrogen::~Hydrogen () inline
Destructor
Definition at line 32 of file Get_Input.hpp.
References hydrogenModules.
Member Function Documentation
getModules()
std::list<Module *> hydrogen_framework::Hydrogen::getModules () inline
Return hydrogenModules
Definition at line 49 of file Get_Input.hpp.
References hydrogenModules.
Referenced by main().
processInputs()
bool hydrogen_framework::Hydrogen::processInputs (int c, char * files[])
Process provided inputs. Returns FALSE if any of the Module cannot be parsed properly.
Definition at line 27 of file Get_Input.cpp.
References hydrogen_framework::Module::getVersion(), hydrogenDemarcation, hydrogenModules, and hydrogen_framework::Module::setModule().
Referenced by main().
validateInputs()
bool hydrogen_framework::Hydrogen::validateInputs (int c, char * files[])
Validate provided inputs. Returns FALSE if any of the provided input is not present.
Definition at line 10 of file Get_Input.cpp.
References hydrogenDemarcation.
Referenced by main().
Field Documentation
hydrogenDemarcation
std::string hydrogen_framework::Hydrogen::hydrogenDemarcation private
Setting demarcation string for inputs
Definition at line 52 of file Get_Input.hpp.
Referenced by Hydrogen(), processInputs(), and validateInputs().
hydrogenModules
std::list<Module *> hydrogen_framework::Hydrogen::hydrogenModules private
Container for storing LLVM Modules
Definition at line 53 of file Get_Input.hpp.
Referenced by getModules(), processInputs(), and ~Hydrogen().
The documentation for this class was generated from the following files:
Get_Input.hpp
Get_Input.cpp