Hydrogen: hydrogen_framework::Graph_Function Class Reference
hydrogen_framework::Graph_Function Class Reference
#include <Graph_Function.hpp>
Public Member Functions
Graph_Function (unsigned id)
~Graph_Function ()
std::string getFunctionFile ()
unsigned getFunctionID ()
std::list< Graph_Line * > getFunctionLines ()
std::string getFunctionName ()
Graph * getGraph ()
bool isFunctionFileSet ()
bool isFunctionLinesEmpty ()
void pushFrontFunctionLines (Graph_Line *line)
void pushFunctionLines (Graph_Line *line)
void setFunctionFile (std::string name)
void setFunctionName (std::string name)
void setGraph (Graph *graph)
Private Attributes
Graph * funcGraph
std::string functionFile
unsigned functionID
std::list< Graph_Line * > functionLines
std::string functionName
Detailed Description
Graph_Function Class: Container for storing source line belonging to a function
Definition at line 19 of file Graph_Function.hpp.
Constructor & Destructor Documentation
Graph_Function()
hydrogen_framework::Graph_Function::Graph_Function (unsigned id) inline
Constructor
Definition at line 24 of file Graph_Function.hpp.
~Graph_Function()
hydrogen_framework::Graph_Function::~Graph_Function () inline
Destructor
Definition at line 29 of file Graph_Function.hpp.
References functionLines.
Member Function Documentation
getFunctionFile()
std::string hydrogen_framework::Graph_Function::getFunctionFile () inline
Return functionFile
Definition at line 79 of file Graph_Function.hpp.
References functionFile.
Referenced by hydrogen_framework::addToMVICFG(), hydrogen_framework::findMatchedLine(), and hydrogen_framework::getNewlyAdded().
getFunctionID()
unsigned hydrogen_framework::Graph_Function::getFunctionID () inline
Return functionID
Definition at line 74 of file Graph_Function.hpp.
References functionID.
getFunctionLines()
std::list<Graph_Line *> hydrogen_framework::Graph_Function::getFunctionLines () inline
Return functionLines
Definition at line 64 of file Graph_Function.hpp.
References functionLines.
Referenced by hydrogen_framework::Graph::addVirtualNodes().
getFunctionName()
std::string hydrogen_framework::Graph_Function::getFunctionName () inline
Return funcName
Definition at line 69 of file Graph_Function.hpp.
References functionName.
Referenced by hydrogen_framework::addToMVICFG(), hydrogen_framework::Graph::addVirtualNodes(), and hydrogen_framework::findMatchedLine().
getGraph()
Graph* hydrogen_framework::Graph_Function::getGraph () inline
Return pointer to encompassing Graph
Definition at line 89 of file Graph_Function.hpp.
References funcGraph.
isFunctionFileSet()
bool hydrogen_framework::Graph_Function::isFunctionFileSet () inline
Return true if functionFile is not empty
Definition at line 44 of file Graph_Function.hpp.
References functionFile.
Referenced by hydrogen_framework::buildICFG().
isFunctionLinesEmpty()
bool hydrogen_framework::Graph_Function::isFunctionLinesEmpty () inline
Return true if functionLines is empty
Definition at line 59 of file Graph_Function.hpp.
References functionLines.
Referenced by hydrogen_framework::buildICFG().
pushFrontFunctionLines()
void hydrogen_framework::Graph_Function::pushFrontFunctionLines (Graph_Line * line)
Push Graph_Line at the front of the functionLines list. Only used for Virtual node
Definition at line 15 of file Graph_Function.cpp.
References functionLines, and hydrogen_framework::Graph_Line::setGraphFunction().
Referenced by hydrogen_framework::Graph::addVirtualNodes().
pushFunctionLines()
void hydrogen_framework::Graph_Function::pushFunctionLines (Graph_Line * line)
Push Graph_Line at the back of the functionLines list
Definition at line 10 of file Graph_Function.cpp.
References functionLines, and hydrogen_framework::Graph_Line::setGraphFunction().
Referenced by hydrogen_framework::Graph::addFunctionCallEdges(), hydrogen_framework::Graph::addVirtualNodes(), and hydrogen_framework::buildICFG().
setFunctionFile()
void hydrogen_framework::Graph_Function::setFunctionFile (std::string name) inline
Set functionFile
Definition at line 39 of file Graph_Function.hpp.
References functionFile.
Referenced by hydrogen_framework::Graph::addFunctionCallEdges(), and hydrogen_framework::buildICFG().
setFunctionName()
void hydrogen_framework::Graph_Function::setFunctionName (std::string name) inline
Set functionName
Definition at line 34 of file Graph_Function.hpp.
References functionName.
Referenced by hydrogen_framework::Graph::addFunctionCallEdges(), hydrogen_framework::addToMVICFG(), and hydrogen_framework::buildICFG().
setGraph()
void hydrogen_framework::Graph_Function::setGraph (Graph * graph) inline
Set pointer to encompassing Graph
Definition at line 84 of file Graph_Function.hpp.
References funcGraph.
Referenced by hydrogen_framework::Graph::pushGraphFunction().
Field Documentation
funcGraph
Graph* hydrogen_framework::Graph_Function::funcGraph private
Points to the Graph that encompasses this
Definition at line 96 of file Graph_Function.hpp.
Referenced by getGraph(), and setGraph().
functionFile
std::string hydrogen_framework::Graph_Function::functionFile private
Name of the file in which the function resides
Definition at line 94 of file Graph_Function.hpp.
Referenced by getFunctionFile(), isFunctionFileSet(), and setFunctionFile().
functionID
unsigned hydrogen_framework::Graph_Function::functionID private
Function Container ID
Definition at line 92 of file Graph_Function.hpp.
Referenced by getFunctionID().
functionLines
std::list<Graph_Line *> hydrogen_framework::Graph_Function::functionLines private
Container for lines in the function
Definition at line 95 of file Graph_Function.hpp.
Referenced by getFunctionLines(), isFunctionLinesEmpty(), pushFrontFunctionLines(), pushFunctionLines(), and ~Graph_Function().
functionName
std::string hydrogen_framework::Graph_Function::functionName private
Name of the function
Definition at line 93 of file Graph_Function.hpp.
Referenced by getFunctionName(), and setFunctionName().
The documentation for this class was generated from the following files:
Graph_Function.hpp
Graph_Function.cpp